[project]
name = "tgmusicbot"
version = "1.2.4"
description = "Telegram Music Bot with full playback support using PyTdBot and PyTgCalls"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Ashok Shau", email = "ashokshau@t.me" },
]
keywords = [
    "telegram",
    "music",
    "bot",
    "async",
    "tdlib",
    "pytgcalls",
    "voicechat",
    "spotify",
    "ytmusic",
    "opensource",
    "pytdbot",
    "py-tgcalls",
    "yt-dlp",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Communications :: Chat :: Telegram",
    "Topic :: Multimedia :: Sound/Audio :: Players",
    "Environment :: Console",
    "Framework :: AsyncIO",
]
dependencies = [
    "aiofiles>=25.1.0",
    "cachetools>=7.1.8",
    "kurigram>=2.2.25",
    "ntgcalls>=2.2.5",
    "pillow>=12.3.0",
    "psutil>=7.2.2",
    "py-tgcalls>=2.3.3",
    "py-yt-search>=0.8.0",
    "pycryptodome>=3.23.0",
    "pydantic>=2.13.5",
    "pymongo>=4.18.0",
    "pytdbot>=0.10.1",
    "pytgcrypto>=1.2.12",
    "ujson>=6.0.0",
    "yt-dlp>=2026.8.19",
]

[project.license]
file = "LICENSE"

[project.optional-dependencies]
dev = [
    "black",
]

[project.scripts]
start = "TgMusic.__main__:main"

[project.urls]
Homepage = "https://github.com/AshokShau/tgmusicbot"
Source = "https://github.com/AshokShau/tgmusicbot"
"Issue Tracker" = "https://github.com/AshokShau/tgmusicbot/issues"

[tool.uv]
package = true

[tool.setuptools]
packages = [
    "TgMusic",
]
